### ISSUE TITLE
CARLI 2 schools in MAS - review merges, matches, sanity check

### ISSUE THREAD

**Issue by patrickzurek** [eXtensibleCatalog/xcmetadataservicestoolkit#364]
JIRA issue created by: rcook
Originally opened: 2012-07-19 01:49 PM

Issue body:

[~jbrand] has run two schools through MAS (he will provide the links in the issue for ease of locating).  I asked a couple of questions:

1.  How many matches did we have between them?
2.  Is that a reasoable number, does it pass the logic test.  Say it is 20K matched bibs...does that seem like enough?
3. I would like CARLI folks to looks at the output and approve, etc.

I want to make sure we are not missing some large subset of records.

[~jgibson] and [~cdelis] Please reivew these and bring Gordon Fellows in too.  I would also suggest Gordon sign up as a user and let me know, I will make him a developer status so he can make comments and add to issues.

**Comment by patrickzurek** [comment]
JIRA Coment by user: jbrand
JIRA Timestamp: 2012-07-19 03:09 PM

Comment body:

I am running the test here:  http://192.17.55.225:8080/MetadataServicesToolkit

Currently I am rerunning the data again, hopefully for the 3rd time through to completion, it is running through the 2nd schools data now, and is not indexed so you won't be able to browse.

But, the 1st 2 times I ran I got the same results (as far as I could tell from comparing logs of what matched).

There are about 9726 match sets.  (made during the run of JCC data against the already existing UIU data.)

File attached showing these.  I will attach another file showing the many matches within UIU data itself later.

**Comment by patrickzurek** [comment]
JIRA Coment by user: jbrand
JIRA Timestamp: 2012-07-19 03:32 PM

Comment body:

Just added the match list for the run of the service for UIU.  There are about 81,500 match sets just from duplicated records within UIU data itself.

Then the service ran the JCC records and found about 9700 more matches, mostly duplicated records between the 2 schools.

**Comment by patrickzurek** [comment]
JIRA Coment by user: rcook
JIRA Timestamp: 2012-07-19 03:48 PM

Comment body:

You said 81500 just at one school.  That seems surprisingly high as I thought we would not expect to find much aggregation in one school.   We should check that, or am I off base?   [~jbowen]

**Comment by patrickzurek** [comment]
JIRA Coment by user: rcook
JIRA Timestamp: 2012-07-23 11:59 AM

Comment body:

[~jgibson] and [~gfellows] Can you look and get some sort of a confort level that MAS is working as expected here.  [~jbrand] Does this mean that 81,500 matched output records are created just at one school?

I am concerned that one school by itself is matching this many time.

1.  Looking just at UIU, can you spot check that the matches where record at the same school match each other and get aggregated.
2.   Any of these suppressed records?
3.  When add 2nd school, do you think that the 9726 are all the new match points that should be expected?


[~jbrand] [~cdelis]

**Comment by patrickzurek** [comment]
JIRA Coment by user: jbrand
JIRA Timestamp: 2012-07-23 12:21 PM

Comment body:

FYI, attached are the files with matching records numbers.  Look at the records themselves at http://192.17.55.225:8080/MetadataServicesToolkit

**Comment by patrickzurek** [comment]
JIRA Comment by user: Jessica Gibson (gibsonjc)
JIRA Timestamp: 2012-07-23 12:30 PM

Comment body:

Thanks for the text files of matches information, [~jbrand].  I had been looking at the file in the Logs > Services > marcaggregation before, and these look like the same lists of matching records without the other log data, I think.  Just to clarify, matches.txt is the matches between JWC records to the UIU records that were loaded first, right?

**Comment by patrickzurek** [comment]
JIRA Coment by user: jbrand
JIRA Timestamp: 2012-07-23 12:37 PM

Comment body:

[~jgibson] You have everything exactly right.  I snipped out the 2 sections of matching details from the margaggregation log file.  The service ran twice, 1st to process UIU records, the 1st file represents matches just within that schools' records.  The second run shows the matches between JWC and UIU records.

**Comment by patrickzurek** [comment]
JIRA Coment by user: rcook
JIRA Timestamp: 2012-07-23 01:52 PM

Comment body:

Just spot checked this one with 5 records, that all seem to have the same OCLC number.

Jessica, are these all valid?  You would have this as 5 bibs instead of 1 bib and separate holdings?

Also, [~jbrand] what are these errors about?

**Comment by patrickzurek** [comment]
JIRA Comment by user: Jessica Gibson (gibsonjc)
JIRA Timestamp: 2012-07-23 02:07 PM

Comment body:

I've checked quite a few of the UIU-only matches today, and thus far, all of the records exist this way in the UIU Voyager database.  (This looks to me like the unfortunate results of their retrospective conversion project back in 2003 that replaced millions of short records will full cataloging based on some rather loose criteria...)  I'm currently running an Access query in their database for duplicate OCLC numbers, and it's been running for over an hour, so I suspect there are A LOT.  This doesn't seem to me to be a problem with the Agg Service; I think it's doing what it should with the data it was given.

I'll move on to checking the UIU-JWC matches next.

**Comment by patrickzurek** [comment]
JIRA Coment by user: rcook
JIRA Timestamp: 2012-07-23 02:19 PM

Comment body:

Looking at the highlighted number from output screen shot and noticed that there is no successor record in the output2 screen shot.

**Comment by patrickzurek** [comment]
JIRA Coment by user: jbrand
JIRA Timestamp: 2012-07-24 08:38 AM

Comment body:

Randy regarding you comment about lack of successor - I think I showed you you were looking at an output record - note the 005, looks like a current timestamp that the service manufactured.

**Comment by patrickzurek** [comment]
JIRA Coment by user: rcook
JIRA Timestamp: 2012-07-24 10:34 AM

Comment body:

Yes John.  The IDs in the report are OAI Ids that the service generated, and not the OCLC or other ID.  Sorry for the confusion.

**Comment by patrickzurek** [comment]
JIRA Comment by user: Jessica Gibson (gibsonjc)
JIRA Timestamp: 2012-07-24 12:06 PM

Comment body:

I see that there are UIU records that match on each other and create an Output Record (I believe correctly for the reasons I mentioned before), but I can't find that any of the UIU and JWC record matches are creating an Output Record.  Is merging records from both institutions not part of this test?  Should I only be looking to see that the correct UIU and JWC records were matched up?

**Comment by patrickzurek** [comment]
JIRA Comment by user: Chris Delis (cedelis)
JIRA Timestamp: 2012-07-24 12:23 PM

Comment body:

I, too, looked at matches.txt in order to find a UIU/JWC merge, but came up empty. I've looked at predecessor recs and they are all UIU.  I also see no "035$a" with JWC, only UIU (which agrees with the fact that the pred recs are all UIU). Maybe I'm searching incorrectly?

**Comment by patrickzurek** [comment]
JIRA Coment by user: jbrand
JIRA Timestamp: 2012-07-24 04:27 PM

Comment body:

There are plenty of matches seen in matches.txt between the 2 schools but apparently none producing output. What I thought was a bug in reporting may be a real issue.

Take this one as a for instance:
*** Matchset In: {34520587, 140927900, }, Out: 0

If you look at the records you see the 140927900 record is a JCC record.  But as Jessica points out you also see, 'produced no output.'  I have seen output before between the schools so wonder if it could have something to do with my last round of changes?

I'm not sure what Chris is saying I'll check into it more.

**Comment by patrickzurek** [comment]
JIRA Comment by user: Chris Delis (cedelis)
JIRA Timestamp: 2012-07-24 04:29 PM

Comment body:

I basically meant that I was not able to find any output records with JWC as a RoS... not just ROS, but even a part of the merge (where I'd expect to see (JWC)bibid in the output record's 035$a...

**Comment by patrickzurek** [comment]
JIRA Coment by user: jbrand
JIRA Timestamp: 2012-07-24 04:40 PM

Comment body:

On Chris's comment - the matches between the 2 schools are primarily on the 035a with the OCoLC prefix.  There were only like say 3 records within JCC that matched each other.  (those 3 may have matched on a JCC prefixed 035a, I don't know right off hand).

There are unexplained errors indexed in browse records.  (e.g. 'null', and 'the record produced no output'), I recommend explaining / fixing these, and rerunning.

**Comment by patrickzurek** [comment]
JIRA Comment by user: Chris Delis (cedelis)
JIRA Timestamp: 2012-07-24 04:48 PM

Comment body:

I can't recall the spec, nor do I recall where the data would go (in the 035$a?  perhaps in a 9XX field?), but I have been expecting to see a field in the RoS output that listed all the org codes in the match set (this would be needed for us to later be able to create a org-based filter (e.g., facet in Drupal). Is there a known example of a UIU and JWC merged record somewhere I can look at?  

Edited: FYI, I do notice that in running unit tests marcagg does seem to correctly do this.  I added two org codes UIUdb and JWCdb to small_35/small.xml and it worked as expected (in the 035$a):


          <marc:datafield ind1=" " ind2=" " tag="035">
            <marc:subfield code="a">(JWCdb)1130480</marc:subfield>
          </marc:datafield>
          <marc:datafield ind1=" " ind2=" " tag="035">
            <marc:subfield code="a">(UIUdb)1012755</marc:subfield>
          </marc:datafield>
          <marc:datafield ind1=" " ind2=" " tag="035">
            <marc:subfield code="a">(WoW)01240630</marc:subfield>
          </marc:datafield>

**Comment by patrickzurek** [comment]
JIRA Coment by user: jbrand
JIRA Timestamp: 2012-07-24 05:42 PM

Comment body:

Oh, now I understand what you are saying.  Yes, the 035$a fields are aggregated and added to the output record.

**Comment by patrickzurek** [comment]
JIRA Coment by user: jbrand
JIRA Timestamp: 2012-07-25 08:49 AM

Comment body:

I found a problem with the merge from 2 different input repos.

Many exceptions during merge of 2 school data like:
19 Jul 2012 16:41:22,583 xc.mst.services.marcaggregation.MarcAggregationService:555 ERROR [SERVICE_7527] - error processing record with id:140910853
java.lang.NullPointerException
        at xc.mst.services.marcaggregation.MASMarcBuilder.getDynamicContent(MASMarcBuilder.java:191)
        at xc.mst.services.marcaggregation.MarcAggregationService.mergeBibSet(MarcAggregationService.java:621)
        at xc.mst.services.marcaggregation.MarcAggregationService.mergeOverlord(MarcAggregationService.java:1090)
        at xc.mst.services.marcaggregation.MarcAggregationService.processBibNewActive(MarcAggregationService.java:1060)
        at xc.mst.services.marcaggregation.MarcAggregationService.processBib(MarcAggregationService.java:923)
        at xc.mst.services.marcaggregation.MarcAggregationService.process(MarcAggregationService.java:470)
        at xc.mst.services.GenericMetadataService.process(GenericMetadataService.java:644)
        at xc.mst.services.impl.service.GenericMetadataService.process(GenericMetadataService.java:24)
        at xc.mst.services.marcaggregation.MarcAggregationService.process(MarcAggregationService.java:421)
        at xc.mst.services.MetadataServiceManager.doSomeWork(MetadataServiceManager.java:81)
        at xc.mst.scheduling.WorkerThread.run(WorkerThread.java:92)

[~cdelis]
I believe the problem is that there are records needed from 2 different input repos.  The service gets started and knows of the current input repo.  If merging with another repo's data, need way to retrieve it.  (need to track where to get it).  Getting a null pointer exception when trying to retrieve an unknown record id from a repo.  I.E. have the JCC repo, get that record xml, then try to get the UIU record xml from the JCC repo too.  Won't work.

**Comment by patrickzurek** [comment]
JIRA Comment by user: Jessica Gibson (gibsonjc)
JIRA Timestamp: 2012-07-25 12:42 PM

Comment body:

In case it is helpful to note something that did work as expected, I located two instances where two JWC records matched on each other with OCLC numbers during this process (but not on any UIU records) and an Output Record was successfully produced:

*** Matchset In: {140920766, 140920767, }, Out: 292789681  
otherwise known as (OCoLC)56721550 or JWCdb IDs 18857 and 18860

*** Matchset In: {140927460, 140927461, }, Out: 292792287  
otherwise known as (OCoLC)06649724 or JWCdb IDs 10409 and 10410

The correct Record of Source was chosen in both cases because the Encoding Levels were different and the higher one in the list was used (record size did not come into play in these instances).

**Comment by patrickzurek** [comment]
JIRA Comment by user: Chris Delis (cedelis)
JIRA Timestamp: 2012-08-08 10:32 AM

Comment body:

[~jgibson], Do you know where I can get a copy of the input records (JWC and UIU) that you have been using for these scenarios? I think I'd like to work on fixing this issue so that you may proceed with further analysis of marcagg.  Thanks!

Edit: Never mind.  I found it at file:///xc/file_harvest/jwcc_full and file:///xc/file_harvest/uiu_full on server 192.17.55.225.

**Comment by patrickzurek** [comment]
JIRA Coment by user: rcook
JIRA Timestamp: 2013-01-24 10:47 AM

Comment body:

[~cdelis] and Jessica,   Just checking, where did things end up with this test, the sanity check of two schools?   I know the focus of late has been on the small set use case testing.

**Comment by patrickzurek** [comment]
JIRA Comment by user: Chris Delis (cedelis)
JIRA Timestamp: 2013-01-24 10:58 AM

Comment body:

This issue was fixed in rev. 3474 (but I forgot to update the jira issue):

Fixed remerge(). If a deleted record happens to belong to a merge set, MAS
attempted to merge the deleted record, but failed (NPE). We now delete merge
data for the deleted record *before* remerging the set, and also not including
it in the new merge set.

**Comment by patrickzurek** [comment]
JIRA Comment by user: Chris Delis (cedelis)
JIRA Timestamp: 2013-01-24 10:58 AM

Comment body:

rev. 3474

**Comment by patrickzurek** [comment]
Issue resolved: 2013-01-24 10:58 AM
