### ISSUE TITLE
needed rights to run optimization script

### ISSUE THREAD

**Issue by patrickzurek** [eXtensibleCatalog/xcmetadataservicestoolkit#387]
JIRA issue created by: jbrand
Originally opened: 2012-06-22 10:55 AM

Issue body:

jbrand@xc-brand:/xc/MST-instances/MetadataServicesToolkit$ ./optimize_solr_index.sh
log4j:WARN No appenders could be found for logger (org.apache.solr.core.SolrResourceLoader).
log4j:WARN Please initialize the log4j system properly.
java.io.IOException: background merge hit exception: _4el(3.3):C500000 _460(3.3):C500000 _47f(3.3):C500000 _3yy(3.3):C500000 _44l(3.3):C500000 _41r(3.3):C500000 _436(3.3):C500000 _3xj(3.3):C500000 _40d(3.3):C500000 _4aa(3.3):C500000 _4d6(3.
3):C500000 _48w(3.3):C500000 _4br(3.3):C500000 _2ve(3.3):C10000 _3yr(3.3):C10000 _4et(3.3):C10000 _4er(3.3):C10000 _4es(3.3):C10000 _4em(3.3):C10000 _4eo(3.3):C10000 _4en(3.3):C10000 _4eq(3.3):C10000 _4ep(3.3):C10000 _4eu(3.3):C10000 _4c2(3
.3):C10000 _4bm(3.3):C10000 _4b0(3.3):C10000 _4b4(3.3):C10000 _4ev(3.3):C10000 _4ew(3.3):C6579 into _4ex [optimize]
        at org.apache.lucene.index.IndexWriter.optimize(IndexWriter.java:2541)
        at org.apache.lucene.index.IndexWriter.optimize(IndexWriter.java:2461)
        at org.apache.solr.update.DirectUpdateHandler2.commit(DirectUpdateHandler2.java:410)
        at xc.mst.utils.OptimizeSolrIndex.commit(OptimizeSolrIndex.java:45)
        at xc.mst.utils.OptimizeSolrIndex.main(OptimizeSolrIndex.java:53)
Caused by: java.io.FileNotFoundException: /xc/MST-instances/MetadataServicesToolkit/solr/data/index/_4ex.fnm (Permission denied)
        at java.io.RandomAccessFile.open(Native Method)
        at java.io.RandomAccessFile.<init>(RandomAccessFile.java:216)
        at org.apache.lucene.store.FSDirectory$FSIndexOutput.<init>(FSDirectory.java:441)
        at org.apache.lucene.store.FSDirectory.createOutput(FSDirectory.java:306)
        at org.apache.lucene.index.FieldInfos.write(FieldInfos.java:312)
        at org.apache.lucene.index.SegmentMerger.mergeFields(SegmentMerger.java:223)
        at org.apache.lucene.index.SegmentMerger.merge(SegmentMerger.java:107)
        at org.apache.lucene.index.IndexWriter.mergeMiddle(IndexWriter.java:4217)
        at org.apache.lucene.index.IndexWriter.merge(IndexWriter.java:3859)
        at org.apache.lucene.index.ConcurrentMergeScheduler.doMerge(ConcurrentMergeScheduler.java:388)
        at org.apache.lucene.index.ConcurrentMergeScheduler$MergeThread.run(ConcurrentMergeScheduler.java:456)

**Comment by patrickzurek** [comment]
JIRA Coment by user: jbrand
JIRA Timestamp: 2012-06-22 10:59 AM

Comment body:

possible solutions:

run under sudo (seems to work, requires your account to be in sudoers file)
sudo ./optimize_solr_index.sh

or possibly changing owner and group of ./optimize_solr_index.sh allow access (probably will work?)

**Comment by patrickzurek** [comment]
JIRA Coment by user: jbrand
JIRA Timestamp: 2012-07-25 11:38 AM

Comment body:

I documented changes needed here http://code.google.com/p/xcmetadataservicestoolkit/wiki/OptimizeSolrIndex
