### ISSUE TITLE
bad data for 020a caused MAS to crash during insert into database

### ISSUE THREAD

**Issue by patrickzurek** [eXtensibleCatalog/xcmetadataservicestoolkit#395]
JIRA issue created by: jbrand
Originally opened: 2012-06-06 01:56 PM

Issue body:

harvested all in UIUdb (21 million), normalized, and it ran 8921000 records out of 21312514 through marcaggregation before crashing because:

06 Jun 2012 08:50:23,197 xc.mst.services.impl.service.GenericMetadataService:26 ERROR [SERVICE_10343] - GenericMetadataService, processing repo marcnormalization2 failed.
org.springframework.dao.DataIntegrityViolationException: StatementCallback; SQL [load data infile '/xc/MST-instances/MetadataServicesToolkit/db_load.in' REPLACE into table matchpoints_020a character set utf8 fiel
ds terminated by '\t' lines terminated by '\n']; Row 1 doesn't contain data for all columns; nested exception is java.sql.SQLException: Row 1 doesn't contain data for all columns
        at org.springframework.jdbc.support.SQLStateSQLExceptionTranslator.doTranslate(SQLStateSQLExceptionTranslator.java:101)
        at org.springframework.jdbc.support.AbstractFallbackSQLExceptionTranslator.translate(AbstractFallbackSQLExceptionTranslator.java:72)
        at org.springframework.jdbc.support.AbstractFallbackSQLExceptionTranslator.translate(AbstractFallbackSQLExceptionTranslator.java:80)
        at org.springframework.jdbc.support.AbstractFallbackSQLExceptionTranslator.translate(AbstractFallbackSQLExceptionTranslator.java:80)
        at org.springframework.jdbc.core.JdbcTemplate.execute(JdbcTemplate.java:406)
        at org.springframework.jdbc.core.JdbcTemplate.execute(JdbcTemplate.java:427)
        at xc.mst.services.marcaggregation.dao.MarcAggregationServiceDAO.replaceIntoTable(MarcAggregationServiceDAO.java:453)
        at xc.mst.services.marcaggregation.dao.MarcAggregationServiceDAO.persist1StrMatchpointMaps(MarcAggregationServiceDAO.java:171)
        at xc.mst.services.marcaggregation.matcher.ISBNMatcher.flush(ISBNMatcher.java:217)
        at xc.mst.services.marcaggregation.MarcAggregationService.commitIfNecessary(MarcAggregationService.java:1298)
        at xc.mst.services.GenericMetadataService.process(GenericMetadataService.java:745)
        at xc.mst.services.impl.service.GenericMetadataService.process(GenericMetadataService.java:24)
        at xc.mst.services.marcaggregation.MarcAggregationService.process(MarcAggregationService.java:397)
        at xc.mst.services.MetadataServiceManager.doSomeWork(MetadataServiceManager.java:81)
        at xc.mst.scheduling.WorkerThread.run(WorkerThread.java:92)
        at java.lang.Thread.run(Thread.java:662)
Caused by: java.sql.SQLException: Row 1 doesn't contain data for all columns
        at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:946)
        at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:2985)
        at com.mysql.jdbc.MysqlIO.sendCommand(MysqlIO.java:1631)
        at com.mysql.jdbc.MysqlIO.sqlQueryDirect(MysqlIO.java:1723)
        at com.mysql.jdbc.Connection.execSQL(Connection.java:3277)
        at com.mysql.jdbc.Connection.execSQL(Connection.java:3206)
        at com.mysql.jdbc.Statement.execute(Statement.java:727)
        at org.apache.commons.dbcp.DelegatingStatement.execute(DelegatingStatement.java:264)
        at org.springframework.jdbc.core.JdbcTemplate$1ExecuteStatementCallback.doInStatement(JdbcTemplate.java:420)
        at org.springframework.jdbc.core.JdbcTemplate.execute(JdbcTemplate.java:395)
        ... 11 more
06 Jun 2012 08:50:23,493 xc.mst.services.marcaggregation.MarcAggregationService:400 ERROR [SERVICE_10343] - MarcAggregationService, processing repo marcnormalization2 failed.
java.lang.RuntimeException: org.springframework.dao.DataIntegrityViolationException: StatementCallback; SQL [load data infile '/xc/MST-instances/MetadataServicesToolkit/db_load.in' REPLACE into table matchpoints_
020a character set utf8 fields terminated by '\t' lines terminated by '\n']; Row 1 doesn't contain data for all columns; nested exception is java.sql.SQLException: Row 1 doesn't contain data for all columns
        at xc.mst.services.impl.service.GenericMetadataService.process(GenericMetadataService.java:27)
        at xc.mst.services.marcaggregation.MarcAggregationService.process(MarcAggregationService.java:397)
        at xc.mst.services.MetadataServiceManager.doSomeWork(MetadataServiceManager.java:81)
        at xc.mst.scheduling.WorkerThread.run(WorkerThread.java:92)
        at java.lang.Thread.run(Thread.java:662)
Caused by: org.springframework.dao.DataIntegrityViolationException: StatementCallback; SQL [load data infile '/xc/MST-instances/MetadataServicesToolkit/db_load.in' REPLACE into table matchpoints_020a character se
t utf8 fields terminated by '\t' lines terminated by '\n']; Row 1 doesn't contain data for all columns; nested exception is java.sql.SQLException: Row 1 doesn't contain data for all columns
        at org.springframework.jdbc.support.SQLStateSQLExceptionTranslator.doTranslate(SQLStateSQLExceptionTranslator.java:101)
        at org.springframework.jdbc.support.AbstractFallbackSQLExceptionTranslator.translate(AbstractFallbackSQLExceptionTranslator.java:72)
        at org.springframework.jdbc.support.AbstractFallbackSQLExceptionTranslator.translate(AbstractFallbackSQLExceptionTranslator.java:80)
        at org.springframework.jdbc.support.AbstractFallbackSQLExceptionTranslator.translate(AbstractFallbackSQLExceptionTranslator.java:80)
        at org.springframework.jdbc.core.JdbcTemplate.execute(JdbcTemplate.java:406)
        at org.springframework.jdbc.core.JdbcTemplate.execute(JdbcTemplate.java:427)

**Comment by patrickzurek** [comment]
JIRA Coment by user: jbrand
JIRA Timestamp: 2012-06-08 10:38 AM

Comment body:

Unfortunately there was not enough in the log to figure out what record was bad.  I did 2 things - I looked in the code to try to tighten up ISBN/ISSN to make sure an 'empty' string never gets by to be inserted.  But I have a feeling the string is not empty, but just some weird character that the database does not like.  So I also added to the exception handling to spew out the record number if this happens again, so I can look at the record.  Have now restarted the MAS processing.  

I tried just updating the service and restarting, but the update mode of the service was horrifically slow (another issue).  So to restart MAS from scratch:

deleted the processing rules related to MAS.
deleted MAS service.
dropped the database.
readded the service and the processing rule.

It is now running the 21 million UIUdb records again through MAS.

**Comment by patrickzurek** [comment]
JIRA Coment by user: jbrand
JIRA Timestamp: 2012-06-13 11:08 AM

Comment body:

I found in the database for matchpoints_020a a number of clearly bad pieces of data.  I shared with Jennifer and solicited her opinion on a way to improve data collection of 020a items without onerous performance implications.  The following addition was made last night - check to make sure the 1st character of an ISBN is a digit, if not, log an error.  This did in fact clean up the data, I found no suspect data in the database after last night's run.

But...

It failed again during processing at the same point in time.  Today I will restart, catch the exception, not try to fix it, as that strategy clearly has not worked.  I will catch it, so the system can complete processing so I can see the data in record id=30232779 - then hopefully it will be obvious what is going on.

**Comment by patrickzurek** [comment]
JIRA Coment by user: jbrand
JIRA Timestamp: 2012-06-13 11:09 AM

Comment body:

I just tracked down the 'bad' data, unfortunately, it looks decent (possibly acceptable as ISBN?)  I may need to do some special processing, escaping of characters.

cat ./db_load.in
0120546507\     30232779

JohnB@JohnBXC-FNF0BF1 /cygdrive/c/dev/xc/mst/svn/branches/marc_agg/mst-service/custom/MARCAggregation
$ mysql -u root --password=root -D xc_marcaggregation -e "load data infile './db_load.in' REPLACE into table xc_marcaggregation.matchpo
ints_022a character set utf8 fields terminated by '\t' lines terminated by '\n'"
ERROR 1261 (01000) at line 1: Row 1 doesn't contain data for all columns

**Comment by patrickzurek** [comment]
JIRA Coment by user: jbrand
JIRA Timestamp: 2012-06-13 11:16 AM

Comment body:

putting quotes around the whole string works and is fairly innocuous.

'0120546507\'	30232779

**Comment by patrickzurek** [comment]
JIRA Coment by user: jbrand
JIRA Timestamp: 2012-06-14 09:21 AM

Comment body:

went past the problem record during last night's run

**Comment by patrickzurek** [comment]
JIRA Coment by user: jbrand
JIRA Timestamp: 2012-06-28 01:04 PM

Comment body:

my 'solution' seems to have had a very negative side effect, on unix, the matching doesn't seem to be working - it appears to be because the matchpoints now get inserted into the db with single quotes around them.  That was not my intent.

Experimenting with other solutions.

I believe it will be some combination of normalizing the data (i.e. \\ sub'd in for every \) and /or adding to load data infile the fact that fields are optionally single-quoted.

**Comment by patrickzurek** [comment]
JIRA Coment by user: jbrand
JIRA Timestamp: 2012-06-28 01:05 PM

Comment body:

how funny in the above comment the backslashes are gone.  you'll have to imagine them!

**Comment by patrickzurek** [comment]
JIRA Coment by user: jbrand
JIRA Timestamp: 2012-06-29 12:54 PM

Comment body:

created a test case , which passes, and the big run of data made it past this record, and the data is now in the database without the quotes.  So I think we are good here.  Leaving open this time for another day or 2 though to be sure.

**Comment by patrickzurek** [comment]
JIRA Coment by user: jbrand
JIRA Timestamp: 2012-07-02 09:03 AM

Comment body:

retested - all CARLI data from UIU and JCC made it into db, matches were made, etc.

**Comment by patrickzurek** [comment]
Issue resolved: 2012-07-02 09:03 AM
