### ISSUE TITLE
SaxMarcXmlParser exception

### ISSUE THREAD

**Issue by patrickzurek** [eXtensibleCatalog/xcmetadataservicestoolkit#403]
JIRA issue created by: jbrand
Originally opened: 2012-05-24 01:32 PM

Issue body:

processing CARLI UIUdb data, got an exception:

22 May 2012 18:31:28,337 xc.mst.services.GenericMetadataService:647 ERROR [SERVICE_16356] - error processing record w/ id: 4617305
java.lang.NumberFormatException: For input string: "10-"
        at java.lang.NumberFormatException.forInputString(NumberFormatException.java:48)
        at java.lang.Integer.parseInt(Integer.java:458)
        at java.lang.Integer.parseInt(Integer.java:499)
        at xc.mst.bo.record.SaxMarcXmlRecord.endElement(SaxMarcXmlRecord.java:106)

There are '10-' strings within 880 fields such as:

<marc:datafield ind1="0" ind2=" " tag="880">
    <marc:subfield code="6">10-05/$1</marc:subfield>
    <marc:subfield code="a">中国共产党</marc:subfield>
    <marc:subfield code="x">Party work</marc:subfield>
    <marc:subfield code="x">History.</marc:subfield>
  </marc:datafield>

Should SaxMarcXmlRecord handle this data?

**Comment by patrickzurek** [comment]
JIRA Coment by user: rcook
JIRA Timestamp: 2012-05-29 01:12 PM

Comment body:

John,

Where is this failing?  Meaning, are these general problems that are being encountered in say the Norm service that we are seeing now because of dealing with CARLI data, or are these things you are seeing in MAS?

Either way, input from [~jbowen] needed?

**Comment by patrickzurek** [comment]
JIRA Coment by user: jbrand
JIRA Timestamp: 2012-05-29 02:46 PM

Comment body:

Sorry,  this occured during MAS processing, but it uses general purpose parser also used by the transformation service.  [~jbowen] is the above 880 field valid?  Looks like it might be according to the standard?


Stack trace:

22 May 2012 18:31:28,337 ERROR [SERVICE_16356] - error processing record w/ id: 4617305
java.lang.NumberFormatException: For input string: "10-"
        at java.lang.NumberFormatException.forInputString(NumberFormatException.java:48)
        at java.lang.Integer.parseInt(Integer.java:458)
        at java.lang.Integer.parseInt(Integer.java:499)
        at xc.mst.bo.record.SaxMarcXmlRecord.endElement(SaxMarcXmlRecord.java:106)
        at org.apache.xerces.parsers.AbstractSAXParser.endElement(Unknown Source)
        at org.apache.xerces.impl.XMLNSDocumentScannerImpl.scanEndElement(Unknown Source)
        at org.apache.xerces.impl.XMLDocumentFragmentScannerImpl$FragmentContentDispatcher.dispatch(Unknown Source)
        at org.apache.xerces.impl.XMLDocumentFragmentScannerImpl.scanDocument(Unknown Source)
        at org.apache.xerces.parsers.XML11Configuration.parse(Unknown Source)
        at org.apache.xerces.parsers.XML11Configuration.parse(Unknown Source)
        at org.apache.xerces.parsers.XMLParser.parse(Unknown Source)
        at org.apache.xerces.parsers.AbstractSAXParser.parse(Unknown Source)
        at xc.mst.bo.record.SaxMarcXmlRecord.<init>(SaxMarcXmlRecord.java:67)
        at xc.mst.services.marcaggregation.MarcAggregationService.process(MarcAggregationService.java:404)
        at xc.mst.services.GenericMetadataService.process(GenericMetadataService.java:644)
        at xc.mst.services.impl.service.GenericMetadataService.process(GenericMetadataService.java:24)
        at xc.mst.services.marcaggregation.MarcAggregationService.process(MarcAggregationService.java:383)
        at xc.mst.services.MetadataServiceManager.doSomeWork(MetadataServiceManager.java:81)
        at xc.mst.scheduling.WorkerThread.run(WorkerThread.java:92)
        at java.lang.Thread.run(Thread.java:662)

**Comment by patrickzurek** [comment]
JIRA Coment by user: jbowen
JIRA Timestamp: 2012-05-29 05:05 PM

Comment body:

It looks like a data problem:  in the subfield 6 there should be THREE numbers before the dash, not two. 

<marc:subfield code="6">10-05/$1</marc:subfield>  So Transformation won't know what to do with it.

Are we seeing a lot of these?

**Comment by patrickzurek** [comment]
JIRA Coment by user: jbrand
JIRA Timestamp: 2012-05-30 09:32 AM

Comment body:

[~jbowen] I just checked the log - received only 1 of these errors during the processing completed so far (5.9m JWC, 3.7m UIU)

I am not sure the service is logging this correctly - I noticed the error in my general log - but when I searched for record id 4617305 I find the normalization record but with no successor and with no error attached to it.  There should be an error attached to the record in browse records, right?

**Comment by patrickzurek** [comment]
JIRA Coment by user: jbowen
JIRA Timestamp: 2012-05-30 09:33 AM

Comment body:

Yes, I think there should be an error attached to the record.  Good that there is only one so far - this seems like kind of an anomaly.

**Comment by patrickzurek** [comment]
JIRA Coment by user: jbrand
JIRA Timestamp: 2012-05-30 09:54 AM

Comment body:

adding a no output error for this case.

**Comment by patrickzurek** [comment]
JIRA Coment by user: jbrand
JIRA Timestamp: 2012-05-30 09:54 AM

Comment body:

no need to worry about the parsing error this was because of bad data, but fix so that an error is attached to the record - a no output error.

**Comment by patrickzurek** [comment]
Issue resolved: 2012-05-30 09:54 AM
