### ISSUE TITLE
mysql max_allowed_packet error

### ISSUE THREAD

**Issue by patrickzurek** [eXtensibleCatalog/xcmetadataservicestoolkit#506]
JIRA issue created by: Chris Delis (cedelis)
Originally opened: 2011-10-17 08:35 PM

Issue body:
 (nt)

**Comment by patrickzurek** [comment]
JIRA Comment by user: Chris Delis (cedelis)
JIRA Timestamp: 2011-10-17 08:35 PM

Comment body:

During the SolrTransformationService, I experienced a fatal mysql error.

My guess is that this may have something to do with the fact that the MST was processing a large initial import (13 million records, 7M bib/6M hold).  Perhaps a very long SQL statement ("in" clause?)?  In any case, the workaround was to set max_allowed_packet from 16M to 128M.  This might be something that we need to document...


Service is SolrTransformationService:
14 Oct 2011 00:42:14,955 xc.mst.services.impl.service.SolrTransformationService:4850  INFO [SERVICE_19523]

Exception details:
14 Oct 2011 01:40:12,233 xc.mst.scheduling.WorkerThread:100 ERROR [SERVICE_19523] -org.springframework.dao.TransientDataAccessResourceException: PreparedStatementCallback; SQL []; Pac
ket for query is too large (59179710 > 16776192). You can change this value on the server by setting the max_allowed_packet' variable.; nested exception is com.mysql.jdbc.PacketTooBigException: Packet
 for query is too large (59179710 > 16776192). You can change this value on the server by setting th
e max_allowed_packet' variable.
        at org.springframework.jdbc.support.SQLStateSQLExceptionTranslator.doTranslate(SQLStateSQLEx
ceptionTranslator.java:107)
        at org.springframework.jdbc.support.AbstractFallbackSQLExceptionTranslator.translate(AbstractFallbackSQLExceptionTranslator.java:72)
        at org.springframework.jdbc.support.AbstractFallbackSQLExceptionTranslator.translate(AbstractFallbackSQLExceptionTranslator.java:80)
        at org.springframework.jdbc.support.AbstractFallbackSQLExceptionTranslator.translate(Abstrac
tFallbackSQLExceptionTranslator.java:80)
        at org.springframework.jdbc.core.JdbcTemplate.execute(JdbcTemplate.java:602)
        at org.springframework.jdbc.core.JdbcTemplate.query(JdbcTemplate.java:636)
        at org.springframework.jdbc.core.JdbcTemplate.query(JdbcTemplate.java:661)        at org.springframework.jdbc.core.JdbcTemplate.query(JdbcTemplate.java:681)
        at xc.mst.services.transformation.dao.TransformationDAO.getHoldingIdsToActivate(Transformati
onDAO.java:279)
        at xc.mst.services.transformation.TransformationService.commitIfNecessary(TransformationServ
ice.java:263)
        at xc.mst.services.GenericMetadataService.process(GenericMetadataService.java:689)
        at xc.mst.services.MetadataServiceManager.doSomeWork(MetadataServiceManager.java:81)
        at xc.mst.scheduling.WorkerThread.run(WorkerThread.java:92)        at java.lang.Thread.run(Thread.java:619)
Caused by: com.mysql.jdbc.PacketTooBigException: Packet for query is too large (59179710 > 16776192)
. You can change this value on the server by setting the max_allowed_packet' variable.
        at com.mysql.jdbc.MysqlIO.send(MysqlIO.java:2691)
        at com.mysql.jdbc.MysqlIO.sendCommand(MysqlIO.java:1612)        at com.mysql.jdbc.MysqlIO.sqlQueryDirect(MysqlIO.java:1723)
        at com.mysql.jdbc.Connection.execSQL(Connection.java:3283)
        at com.mysql.jdbc.PreparedStatement.executeInternal(PreparedStatement.java:1332)
        at com.mysql.jdbc.PreparedStatement.executeQuery(PreparedStatement.java:1467)
        at org.apache.commons.dbcp.DelegatingPreparedStatement.executeQuery(DelegatingPreparedStatem
ent.java:93)
        at org.springframework.jdbc.core.JdbcTemplate$1.doInPreparedStatement(JdbcTemplate.java:643)
        at org.springframework.jdbc.core.JdbcTemplate.execute(JdbcTemplate.java:586)        ... 9 more

**Comment by patrickzurek** [comment]
JIRA Coment by user: banderson
JIRA Timestamp: 2011-10-18 12:29 PM

Comment body:

we actually already had this param in our documentation:
http://code.google.com/p/xcmetadataservicestoolkit/wiki/MySQLConfigurations

However, it was set to 16M so I changed it to be 128M as you suggested.  Thanks for sharing your fix.  Let us know if there's any other MySQL fixes you have.  Actually, I just added you as an admin on the mst code.google.com site so you can change this page as you please.

**Comment by patrickzurek** [comment]
Issue resolved: 2011-10-18 12:29 PM
