### ISSUE TITLE
Metadata prefix for incoming records configurable

### ISSUE THREAD

**Issue by patrickzurek** [eXtensibleCatalog/xcmetadataservicestoolkit#519]
JIRA issue created by: banderson
Originally opened: 2011-09-23 07:18 PM

Issue body:
 (nt)

**Comment by patrickzurek** [comment]
JIRA Coment by user: banderson
JIRA Timestamp: 2011-09-23 07:18 PM

Comment body:

After creating logging this issue in koha:
http://bugs.koha-community.org/bugzilla3/show_bug.cgi?id=6876

I realized that our harvester doesn't even care about that.  It only looks at the prefix which is set once and only once.  This may actually be the behavior we want, but if so, we should have aliases or something so that marcxml = marc21.

note: this wouldn't be the "correct" behavior for oai-pmh since prefixes are completely arbitrary.  However, it would probably be the best way to do it.

**Comment by patrickzurek** [comment]
JIRA Coment by user: rcook
JIRA Timestamp: 2011-09-23 08:04 PM

Comment body:

I think we should discuss this.  This seems to fit in with my concern about being able to harvest as broadly as possible and maybe there is a proposal here that will allow us to successfully harvest MORE repos..    Sending a notify to Dave and maybe we can chat at our Monday meeting.

**Comment by patrickzurek** [comment]
JIRA Coment by user: banderson
JIRA Timestamp: 2011-09-27 03:30 PM

Comment body:

What I proposed in yesterday's meeting and what I believe everyone seemed to agree upon was as follows:

The most proper way to handle various metadata formats would be to make them unique based on namespaces.  There are 2 major downsides to doing it this way:

1) Our current design doesn't work this way - our metadata formats are unique per prefix.

2) Koha's default marc21 namespace definition is wrong.

Given the above 2 facts, I'm thinking the most proper way isn't necessarily the best way.  I would propose that we stick with making metadata formats unique based on prefixes, but that we allow for prefix aliases.  This wouldn't be too much additional effort and would allow us to work with repositories like koha out of the box.  We could pre-configure known aliases (like marcxml->marc21) and make it easy to add other aliases to the config file.  The MAJOR downside to this would be if another repository used a known prefix or alias to mean something other than what we've already defined it to mean.  For example, if they used the prefix marcxml to describe dc records.  I'm guessing this isn't a big issue... unless we start getting into schema versions, but I would guess prefixes would be changed to match a version change.  The MINOR downside to this approach is what Jennifer described yesterday - that if a repository uses some arbitrary prefix (but known namespace), that prefix would have to be manually added as an alias to the known prefix.  I'm not that concerned about this since it isn't yet an issue and I can think of simple ways we could fix that in the future.  I believe the approach I've detailed is the simplest, most effective for this moment in time.

**Comment by patrickzurek** [comment]
JIRA Coment by user: jbowen
JIRA Timestamp: 2011-09-27 07:43 PM

Comment body:

Yes, I think as long as the "add a prefix alias" procedure is clearly documented it should not be a problem for libraries to use it.  If a problem ever comes up it can be addressed in the future.

**Comment by patrickzurek** [comment]
JIRA Coment by user: rcook
JIRA Timestamp: 2011-11-14 06:42 PM

Comment body:

I think MST-330 precedes this given the news from Salva that he can make a change to Koha that should get him back functional for now.

And, per discussion at team meeting, this issue will change from creating use of aliases to one of adding config option that allows you to choose incoming MARC21 or marcxml as the prefix.

**Comment by patrickzurek** [comment]
JIRA Coment by user: jbrand
JIRA Timestamp: 2011-11-15 07:47 PM

Comment body:

Just investigating this, tried to harvest from:
http://ec2-46-137-137-152.eu-west-1.compute.amazonaws.com/cgi-bin/koha/oai.pl 

it shows it has marc21, though apparently within the documents themselves, are records with <metadataPrefix>marcxml</metadataPrefix>  (though I have yet to confirm this for myself.

All that it is in general log is an error at marctoxctransformation time:
java.lang.NullPointerException
	at xc.mst.dao.record.MessageDAO.persistMessages(MessageDAO.java:127)
	at xc.mst.services.GenericMetadataService.commitIfNecessary(GenericMetadataService.java:490)
	at xc.mst.services.transformation.TransformationService.commitIfNecessary(TransformationService.java:292)
	at xc.mst.services.GenericMetadataService.process(GenericMetadataService.java:690)
	at xc.mst.services.MetadataServiceManager.doSomeWork(MetadataServiceManager.java:81)
	at xc.mst.scheduling.WorkerThread.run(WorkerThread.java:92)
	at java.lang.Thread.run(Thread.java:662)

**Comment by patrickzurek** [comment]
JIRA Coment by user: rcook
JIRA Timestamp: 2011-11-17 04:32 PM

Comment body:

Deferring until it is raised as a need by a user.
