### ISSUE TITLE
thread stack overrun

### ISSUE THREAD

**Issue by patrickzurek** [eXtensibleCatalog/xcmetadataservicestoolkit#571]
JIRA issue created by: banderson
Originally opened: 2011-08-17 02:03 PM

Issue body:
 (nt)

**Comment by patrickzurek** [comment]
JIRA Coment by user: banderson
JIRA Timestamp: 2011-08-17 02:05 PM

Comment body:

full log here:
http://www.extensiblecatalog.org/doc/MST/support/ahmed_MST_General_log.txt

solution here:
http://pearlin.info/mysql-error-stackoverunthread_stack-fix-mysql-overrunerror-code-1436-thread-stack-overrun/

I actually have a my.cnf already checked in ./server-conf/my.cnf.  We should update this example and make sure we highlight it on the wiki.

27 Jul 2011 09:24:05,328 xc.mst.harvester.HarvestManager:641 ERROR [Thread-14] - An error occurred in insertion 
org.springframework.jdbc.UncategorizedSQLException: CallableStatementCallback; uncategorized SQLException for SQL [{? = call get_next_oai_id(?)}]; SQL state [HY000]; error code [1436]; Thread stack overrun:  8548 bytes used of a 131072 byte stack, and 128000 bytes needed.  Use 'mysqld -O thread_stack=#' to specify a bigger stack.; nested exception is java.sql.SQLException: Thread stack overrun:  8548 bytes used of a 131072 byte stack, and 128000 bytes needed.  Use 'mysqld -O thread_stack=#' to specify a bigger stack.
	at org.springframework.jdbc.support.AbstractFallbackSQLExceptionTranslator.translate(AbstractFallbackSQLExceptionTranslator.java:83)
	at org.springframework.jdbc.support.AbstractFallbackSQLExceptionTranslator.translate(AbstractFallbackSQLExceptionTranslator.java:80)
	at org.springframework.jdbc.support.AbstractFallbackSQLExceptionTranslator.translate(AbstractFallbackSQLExceptionTranslator.java:80)
	at org.springframework.jdbc.core.JdbcTemplate.execute(JdbcTemplate.java:969)
	at org.springframework.jdbc.core.JdbcTemplate.call(JdbcTemplate.java:1003)
	at org.springframework.jdbc.core.simple.AbstractJdbcCall.executeCallInternal(AbstractJdbcCall.java:389)
	at org.springframework.jdbc.core.simple.AbstractJdbcCall.doExecute(AbstractJdbcCall.java:363)
	at org.springframework.jdbc.core.simple.SimpleJdbcCall.executeObject(SimpleJdbcCall.java:159)
	at xc.mst.repo.RepositoryDAO.getNextIdAndIncr(RepositoryDAO.java:224)
	at xc.mst.repo.RepositoryDAO.injectId(RepositoryDAO.java:217)

**Comment by patrickzurek** [comment]
JIRA Coment by user: banderson
JIRA Timestamp: 2011-08-19 08:28 PM

Comment body:

this is just a matter of updating our example my.cnf and making sure the documentation highlights the fact that you should modify your my.cnf.

**Comment by patrickzurek** [comment]
JIRA Coment by user: banderson
JIRA Timestamp: 2011-08-22 07:45 PM

Comment body:

documented here:
http://code.google.com/p/xcmetadataservicestoolkit/wiki/MySQLConfigurations

**Comment by patrickzurek** [comment]
Issue resolved: 2011-08-22 07:45 PM
