### ISSUE TITLE
Harvest Schedule or Processing Directive must be defined

### ISSUE THREAD

**Issue by patrickzurek** [eXtensibleCatalog/xcmetadataservicestoolkit#573]
JIRA issue created by: banderson
Originally opened: 2011-08-17 01:36 PM

Issue body:
 (nt)

**Comment by patrickzurek** [comment]
JIRA Coment by user: banderson
JIRA Timestamp: 2011-08-17 01:37 PM

Comment body:

full log here:
http://www.extensiblecatalog.org/doc/MST/support/ahmed_MST_General_log.txt

26 Jul 2011 05:21:40,723 xc.mst.dao.processing.JobDAO:208 ERROR [http-8080-6] - The following errors occurred: Either the service or harvest schedule or processing directive must be defined.
26 Jul 2011 05:21:40,723 xc.mst.manager.processingDirective.DefaultJobService:63 ERROR [http-8080-6] - Data Exception occured when inserting a Job.
xc.mst.dao.DataException: Either the service or harvest schedule or processing directive must be defined.
	at xc.mst.dao.processing.JobDAO.validateFields(JobDAO.java:209)
	at xc.mst.dao.processing.DefaultJobDAO.insert(DefaultJobDAO.java:730)
	at xc.mst.manager.processingDirective.DefaultJobService.insertJob(DefaultJobService.java:59)
	at xc.mst.manager.repository.DefaultProviderService.markProviderDeleted(DefaultProviderService.java:188)

**Comment by patrickzurek** [comment]
JIRA Coment by user: banderson
JIRA Timestamp: 2011-08-19 07:14 PM

Comment body:

Was able to reproduce.  It happens when you create a repository, but haven't yet harvested any records.  It seems to behave correctly according to the documentation here (last paragraph):
http://code.google.com/p/xcmetadataservicestoolkit/wiki/RepositoryManagement

The only downside is that there is an exception in the logs.  It's not a huge priority, but would be good to not put unnecessary exceptions in the log.
