### ISSUE TITLE
IOException occured when writing jobs to file

### ISSUE THREAD

**Issue by patrickzurek** [eXtensibleCatalog/xcmetadataservicestoolkit#574]
JIRA issue created by: banderson
Originally opened: 2011-08-17 01:34 PM

Issue body:
 (nt)

**Comment by patrickzurek** [comment]
JIRA Coment by user: banderson
JIRA Timestamp: 2011-08-17 01:35 PM

Comment body:

full log found here:
http://www.extensiblecatalog.org/doc/MST/support/ahmed_MST_General_log.txt

26 Jul 2011 04:59:46,977 xc.mst.manager.processingDirective.DefaultJobService:204 ERROR [http-8080-6] - IOException occured when writing jobs to file
java.io.FileNotFoundException: /var/lib/tomcat6/./MST-instances/MetadataServicesToolkit/JobsInQueue.txt (Permission denied)
	at java.io.FileOutputStream.open(Native Method)
	at java.io.FileOutputStream.<init>(FileOutputStream.java:209)
	at java.io.FileOutputStream.<init>(FileOutputStream.java:99)
	at java.io.FileWriter.<init>(FileWriter.java:63)
	at xc.mst.manager.processingDirective.DefaultJobService.writeToFile(DefaultJobService.java:164)
	at xc.mst.manager.processingDirective.DefaultJobService.insertJob(DefaultJobService.java:61)
	at xc.mst.manager.processingDirective.DefaultProcessingDirectiveService.runProcessingDirective(DefaultProcessingDirectiveService.java:186)
	at xc.mst.manager.processingDirective.DefaultProcessingDirectiveService.insertProcessingDirective(DefaultProcessingDirectiveService.java:64)
	at xc.mst.action.processingDirective.AddProcessingDirectiveSetsFormats.addProcessingDirectivesSetsFormats(AddProcessingDirectiveSetsFormats.java:218)

**Comment by patrickzurek** [comment]
JIRA Coment by user: banderson
JIRA Timestamp: 2011-08-19 06:23 PM

Comment body:

this permission should be checked at login time.

**Comment by patrickzurek** [comment]
JIRA Coment by user: rcook
JIRA Timestamp: 2011-10-03 04:58 PM

Comment body:

John, if you wish to lobby for this to be in 1.2 or 1.3, please add some rationale here as I am not clear on the impact.  Thanks

**Comment by patrickzurek** [comment]
JIRA Coment by user: jbrand
JIRA Timestamp: 2011-10-03 05:12 PM

Comment body:

The reason I proposed this go into the next release is I felt (with my initial look) that it could be solved relatively quickly.  This is a check for proper permissions early on, Ben proposes login time.  Then a coherent message can be displayed to the user.  How important this is compared to other problems is a different topic vs. how easy it is to address.

**Comment by patrickzurek** [comment]
JIRA Coment by user: rcook
JIRA Timestamp: 2011-10-03 05:54 PM

Comment body:

We might wish to consider other issues, like 576.

**Comment by patrickzurek** [comment]
JIRA Coment by user: jbrand
JIRA Timestamp: 2011-11-04 07:19 PM

Comment body:

At login check permissions canRead, canWrite of MST directory, can you read/write MST-instances/MetadataServicesToolkit/JobsInQueue.txt ?

If no, put up error on login screen.

**Comment by patrickzurek** [comment]
JIRA Coment by user: jbrand
JIRA Timestamp: 2011-11-22 08:24 PM

Comment body:

created gc issue 321 for this

**Comment by patrickzurek** [comment]
Issue resolved: 2011-11-22 08:24 PM
