### ISSUE TITLE
EditService error

### ISSUE THREAD

**Issue by patrickzurek** [eXtensibleCatalog/xcmetadataservicestoolkit#575]
JIRA issue created by: banderson
Originally opened: 2011-08-17 01:32 PM

Issue body:
 (nt)

**Comment by patrickzurek** [comment]
JIRA Coment by user: banderson
JIRA Timestamp: 2011-08-17 01:33 PM

Comment body:

full log file found here:
http://www.extensiblecatalog.org/doc/MST/support/ahmed_MST_General_log.txt

26 Jul 2011 04:59:00,621 xc.mst.utils.LogWriter:145 ERROR [http-8080-1] - Error adding a new service: The first line of the service configuration file must be the service's name.
26 Jul 2011 04:59:00,623 xc.mst.action.services.EditService:176 ERROR [http-8080-1] - The first line of the service configuration file must be the service's name.
xc.mst.manager.processingDirective.ConfigFileException: The first line of the service configuration file must be the service's name.
	at xc.mst.manager.processingDirective.DefaultServicesService.updateService(DefaultServicesService.java:442)
	at xc.mst.action.services.EditService.editService(EditService.java:140)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)

**Comment by patrickzurek** [comment]
JIRA Coment by user: banderson
JIRA Timestamp: 2011-08-19 04:59 PM

Comment body:

applied quick fix

**Comment by patrickzurek** [comment]
Issue resolved: 2011-08-19 04:59 PM
