### ISSUE TITLE
Transformation failing when there's no 001 and 003

### ISSUE THREAD

**Issue by patrickzurek** [eXtensibleCatalog/xcmetadataservicestoolkit#580]
JIRA issue created by: banderson
Originally opened: 2011-08-10 01:42 PM

Issue body:
 (nt)

**Comment by patrickzurek** [comment]
JIRA Coment by user: banderson
JIRA Timestamp: 2011-08-10 01:42 PM

Comment body:

when attempting a harvest of MARC records out of irplus the transformation service is throwing this exception:

04 Aug 2011 14:26:13,494 xc.mst.scheduling.WorkerThread:93 ERROR [Thread-23] -
java.lang.NullPointerException
        at xc.mst.services.transformation.dao.TransformationDAO.persistBibMaps(TransformationDAO.java:135)
        at xc.mst.services.transformation.TransformationService.commitIfNecessary(TransformationService.java:232)
        at xc.mst.services.GenericMetadataService.process(GenericMetadataService.java:640)
        at xc.mst.services.MetadataServiceManager.doSomeWork(MetadataServiceManager.java:81)
        at xc.mst.scheduling.WorkerThread.run(WorkerThread.java:85)
        at java.lang.Thread.run(Thread.java:662)


This is most likely due to the fact that irplus is not outputting 001s and 003s.  Whatever the culpability of irplus is, the MST should not be throwing NPEs, so we need to fix that.


Questions:
1) what should the transformation service do when there are no 001s or 003s?
2) does irplus output holdings?

I'm putting this in 1.0 just so we don't miss it and can prioritize it accordingly.  Is there a better way to do this?  Should we have a queue milestone that we can review on Thursdays?  So that anything in the queue is something that is waiting to be assigned to another milestone?

**Comment by patrickzurek** [comment]
JIRA Coment by user: rcook
JIRA Timestamp: 2011-08-10 06:49 PM

Comment body:

Couple thoughts.  

I am not sure about the idea of obtaining MARC records from a non-MARC system, Jennifer should advise on that.  The 001 is the record id for the record in the source system.   What is the relevant ID in IRPlus..is it the handle? a url?  something else?   The 003 for an ILS is typically the LC given Institution Code?  What is this going to be if the repository is not an ILS but rather a digital repository?


Nonetheless, the requirements on the service would be the same, that records entering MARC to XC Transformation need to have the data elements in them that the service needs.  Helpful errors should be reported and logged when that is not the case.

Re. Holdings question. IRPlus will not have a holdings concept of a record.

I am comfortable with the idea of leaving in the 1.0 milestone the work of reporting a helpful log message for missing 001 or 003.  I imagine that there will be many institutions that are exporting records from their ILS that will forget to make sure there is an 003.  But, please provide a LOE so we can discuss that further.

**Comment by patrickzurek** [comment]
JIRA Coment by user: rcook
JIRA Timestamp: 2011-08-11 04:30 PM

Comment body:

Opening issue 790 for Jennifer to advise on URResearch harvesting.  This issue is now to just remove the NPE and have the service correctly handle records when "required" data is missing in the record.

**Comment by patrickzurek** [comment]
JIRA Coment by user: jbowen
JIRA Timestamp: 2011-08-17 04:19 PM

Comment body:

Makes sense to me to just have it generate an error now if 001 or 003 is missing.  The next question will be whether or not we want to alter the way the 1.0 service works at some point so that we can process UR Research records that lack 001 and 003, or just wait for Transformation 2.0.  I think the 003 is more necessary than the 001, so that would be easier to fix in the service.  We could then ask Nate to generate an 003 NRU in the MARC output, which is technically correct.  It might be useful just to get the service to run, although I don't think it's our idea long-term solution.  But if we really want to get UR Research into the demo sooner rather than later.

**Comment by patrickzurek** [comment]
JIRA Coment by user: rcook
JIRA Timestamp: 2011-08-17 04:27 PM

Comment body:

I don' think handling this is something to address with the current services.

If we wish to get URResearch data into a demo sooner rather than later, why wouldn't we harvest it as DCTerms?  I think all the records that have better than DCTerms type data, e.g. MARC, will have corresponding MARC records in Voyager.

**Comment by patrickzurek** [comment]
JIRA Coment by user: jbrand
JIRA Timestamp: 2011-08-19 03:42 PM

Comment body:

For 1.0 catch exception (estimate is for the 1.0 work)

**Comment by patrickzurek** [comment]
JIRA Coment by user: jbrand
JIRA Timestamp: 2011-11-17 07:25 PM

Comment body:

This was fixed - fogbugz issue 790

**Comment by patrickzurek** [comment]
JIRA Coment by user: jbrand
JIRA Timestamp: 2011-11-22 08:56 PM

Comment body:

gc issue 324

**Comment by patrickzurek** [comment]
Issue resolved: 2011-11-17 07:25 PM
