### ISSUE TITLE
NullPointerException replying to ListSets request

### ISSUE THREAD

**Issue by patrickzurek** [eXtensibleCatalog/xcmetadataservicestoolkit#618]
JIRA issue created by: jbrand
Originally opened: 2011-07-08 06:35 PM

Issue body:
 (nt)

**Comment by patrickzurek** [comment]
JIRA Coment by user: jbrand
JIRA Timestamp: 2011-07-08 06:35 PM

Comment body:

log:

07 Jul 2011 16:09:52,011 xc.mst.utils.LogWriter:130 ERROR [http-8080-5] - An unexpected error occurred while executing the ListSets request.
07 Jul 2011 16:12:17,836 xc.mst.utils.LogWriter:66  INFO [http-8080-5] - Received the OAI request verb=ListRecords&metadataPrefix=xc


stack:
java.lang.NullPointerException
        at xc.mst.oai.Facade.doListSets(Facade.java:477)
        at xc.mst.oai.Facade.execute(Facade.java:224)
        at xc.mst.action.oai.OaiRepository.execute(OaiRepository.java:125)

related to 712?

**Comment by patrickzurek** [comment]
JIRA Coment by user: jbrand
JIRA Timestamp: 2011-07-13 02:15 PM

Comment body:

This definitely could be related to 712, with the fix for 712 taking care of this one, IMO.  I am putting in debug code to verify, but since I have not figured a way to reproduce this, it should go to 'monitor' mode.

**Comment by patrickzurek** [comment]
Issue resolved: 2011-08-12 07:58 PM
