### ISSUE TITLE
NullPointerException in HarvestManager

### ISSUE THREAD

**Issue by patrickzurek** [eXtensibleCatalog/xcmetadataservicestoolkit#649]
JIRA issue created by: banderson
Originally opened: 2011-06-14 12:54 PM

Issue body:
 (nt)

**Comment by patrickzurek** [comment]
JIRA Coment by user: banderson
JIRA Timestamp: 2011-06-14 12:54 PM

Comment body:

Exception in thread "Thread-31" java.lang.NullPointerException
        at xc.mst.harvester.HarvestManager.finishInner(HarvestManager.java:159)
        at xc.mst.scheduling.WorkerThread.finish(WorkerThread.java:138)
        at xc.mst.scheduling.WorkerThread.run(WorkerThread.java:87)
        at java.lang.Thread.run(Thread.java:619)


    @Override
    public void finishInner(boolean success) {
        super.finishInner(success);
        RecordCounts mostRecentIncomingRecordCounts =
            getRecordCountsDAO().getMostRecentIncomingRecordCounts(repo.getName());
        // I'm substracting 1s from startTime because they might actually be equal by the second
        if (mostRecentIncomingRecordCounts.getHarvestStartDate().getTime() >= (startTime - 1000)) {
            for (RecordCounts rc : new RecordCounts[] {
                    mostRecentIncomingRecordCounts,
                    getRecordCountsDAO().getTotalIncomingRecordCounts(repo.getName())
            }) {
                LOG.debug("harvestSchedule: "+harvestSchedule);
                LOG.debug("harvestSchedule.getProvider(): "+harvestSchedule.getProvider());
                LOG.debug("harvestSchedule.getProvider().getLogFileName(): "+harvestSchedule.getProvider().getLogFileName());
                LOG.debug("rc: "+rc);
                LOG.debug("repo: "+repo);
                LogWriter.addInfo(harvestSchedule.getProvider().getLogFileName(), rc.toString(repo.getName()));
            }
            LogWriter.addInfo(harvestSchedule.getProvider().getLogFileName(), repo.getRecordStatsByType());
        }
    }

**Comment by patrickzurek** [comment]
JIRA Coment by user: jbrand
JIRA Timestamp: 2011-06-14 01:39 PM

Comment body:

Note - this occurred on June 8th, the system was updated with newest MST on June 10th.  So not sure if this is still a problem - will add debug code to check to see what is null in case I see this again.

**Comment by patrickzurek** [comment]
JIRA Coment by user: jbrand
JIRA Timestamp: 2011-06-24 05:38 PM

Comment body:

Note - I saw this occur during a unit test where the input files were bad format (marctoxctransformation mock harvest test).  So when it bubbled down to print record counts, they were null.  Added some null checks, and print out 'no record counts available' type statement.

**Comment by patrickzurek** [comment]
JIRA Coment by user: jbrand
JIRA Timestamp: 2011-06-24 05:39 PM

Comment body:

I believe this is resolved.  See above analysis.  Keeping open while we server test in case we re-encounter, if not, I recommend it be closed.

**Comment by patrickzurek** [comment]
Issue resolved: 2011-06-24 05:39 PM
