### ISSUE TITLE
Error in transformation: Cannot add duplicate attribute

### ISSUE THREAD

**Issue by patrickzurek** [eXtensibleCatalog/xcmetadataservicestoolkit#650]
JIRA issue created by: banderson
Originally opened: 2011-06-14 12:52 PM

Issue body:
 (nt)

**Comment by patrickzurek** [comment]
JIRA Coment by user: banderson
JIRA Timestamp: 2011-06-14 12:52 PM

Comment body:

devuser@xcmst2 > grep -c 'Cannot add duplicate attribute' ./MST-instances/MetadataServicesToolkit/logs/MST_General_log.txt 
8

You can see it hasn't effected very many records, so I've had it low on the priority list.  Nevertheless, it'd be good to fix at some point.

11 Jun 2011 09:36:09,205 xc.mst.services.transformation.TransformationService:417 ERROR [Thread-21] - error processing record with id:11993607
org.jdom.IllegalAddException: Cannot add duplicate attribute
        at org.jdom.AttributeList.add(AttributeList.java:162)
        at org.jdom.AttributeList.addAll(AttributeList.java:254)
        at org.jdom.AttributeList.clearAndSet(AttributeList.java:300)
        at org.jdom.Element.setAttributes(Element.java:1095)
        at org.jdom.Element.setAttributes(Element.java:1107)
        at xc.mst.services.impl.service.transformation.XCRecordService.addElement(XCRecordService.java:245)
        at xc.mst.services.impl.service.SolrTransformationService.processFieldAttributeFromSubfield(SolrTransformationService.java:4768)
        at xc.mst.services.impl.service.SolrTransformationService.process776(SolrTransformationService.java:3087)
        at xc.mst.services.transformation.TransformationService.processBibliographicRecord(TransformationService.java:522)
        at xc.mst.services.transformation.TransformationService.process(TransformationService.java:308)
        at xc.mst.services.GenericMetadataService.process(GenericMetadataService.java:569)
        at xc.mst.services.MetadataServiceManager.doSomeWork(MetadataServiceManager.java:80)
        at xc.mst.scheduling.WorkerThread.run(WorkerThread.java:74)
        at java.lang.Thread.run(Thread.java:619)
11 Jun 2011 09:36:10,404 xc.mst.dao.record.RecordCountsDAO:113  INFO [Thread-21] -

**Comment by patrickzurek** [comment]
JIRA Coment by user: rcook
JIRA Timestamp: 2011-09-30 06:58 PM

Comment body:

Not quite sure what this means, ow many records we might possible be trying to add duplicate attributes for, is it valid even, and what is the "cost" in metadata by not fixing this yet.

**Comment by patrickzurek** [comment]
JIRA Coment by user: jbrand
JIRA Timestamp: 2011-10-04 04:01 PM

Comment body:

This is an exception seen in our logs when processing UR data.  It is not seen very often (<10 times I believe).  Would need to find the offending record along with properly handling the exception.  6 hour estimate.

**Comment by patrickzurek** [comment]
JIRA Coment by user: rcook
JIRA Timestamp: 2011-10-04 07:38 PM

Comment body:

Invalid to create two attributes.  Handling two such as ISBN 10 and ISBN13 needs to be addressed by creating both types in the schema.

**Comment by patrickzurek** [comment]
JIRA Coment by user: rcook
JIRA Timestamp: 2011-10-04 07:51 PM

Comment body:

Create first attribute and ignore the second so that the record processes.  Create log entry of 2nd being skipped so that clean up could happen.  Service logs.

**Comment by patrickzurek** [comment]
JIRA Coment by user: rcook
JIRA Timestamp: 2011-10-04 07:55 PM

Comment body:

This is help message.  "Cannot supply two attributes of the same type, second attribute skipped".  

Error message is "Cannot supply 2 attributes"

**Comment by patrickzurek** [comment]
JIRA Coment by user: jbrand
JIRA Timestamp: 2011-11-22 08:54 PM

Comment body:

created gc issue 322

**Comment by patrickzurek** [comment]
JIRA Coment by user: jbrand
JIRA Timestamp: 2011-11-23 01:06 PM

Comment body:

Had a bug when server testing, so based on this, adding another 4 hours for this fix - problem was when server testing there were additional fields found with duplicate attributes - 773,776, 780 - my original logs did not show errors with any of these - anyway, handle most of them, and if software encounters an unexpected one, log it, and continue to process the record.  Don't discard the record for this reason.

**Comment by patrickzurek** [comment]
Issue resolved: 2011-11-23 01:06 PM
